# Allwinner T527 (A523 family) Cortex-A55 octa core 2/4GB RAM, 2x GbE, USB3, USB-C, LCD
BOARD_NAME="Avaota A1"
BOARD_VENDOR="allwinner"
BOARDFAMILY="sun55iw3"
BOARD_MAINTAINER=""
INTRODUCED="2024"
BOOTCONFIG="avaota-a1_defconfig"
OVERLAY_PREFIX="sun55i-t527"
KERNEL_TARGET="edge"
BOOT_FDT_FILE="sun55i-t527-avaota-a1.dtb"
HAS_VIDEO_OUTPUT=no
SERIALCON="ttyAS0"
